trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    displayName: 'Build & Test Plugin'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: "-Xmx8192m"

  - task: Gradle@3
    displayName: 'Verify Plugin Compatibility'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'runPluginVerifier'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: "-Xmx8192m"