name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish Plugin to Jetbrains Marketplace
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        env:
          MARKETPLACE_TOKEN: ${{ secrets.JETBRAINSPLUGINSPECTRALMARKETPLACETOKEN }}
          SIGNING_PASSWORD: ${{ secrets.JETBRAINS_MARKETPLACE_CERTIFICATE_PASSWORD }}
        with:
          arguments: publishPlugin